Update swagger config to support getById, getAll, update, and delete for merchant redirect QRs
vippsas/vipps-qr-api pull request #14
Opened 2022-01-27 14:15 UTC by kaffikaffi

This PR adds some new types, and configurations for endpoints regarding getById, getAll, update, and delete for merchant redirect QRs. 

This makes it possible to get all QRs from one saleunit, and the response will be like this:
```json
[
  {
    "id": "billboard_1",
    "url": "https://qr.vipps.no/generate/qr.png?..."
  },
  {
    "id": "billboard_2",
    "url": "https://qr.vipps.no/generate/qr.png?..."
  }
]
```
It also makes it possible to get by id, and update, but the response is the same as the post-endpoint.
Delete will return HTTP status code.

2022-01-27 14:58 UTC, khenrichsen requested changes

2022-01-27 14:58 UTC, khenrichsen commented on docs/swagger.yaml
> +        '400':
use the same schema for error as is used by the other endpoints

2022-01-27 14:58 UTC, khenrichsen commented on docs/swagger.yaml
> +      summary: Get all saleunit QRs
"Get all Merchant Redirect QRs"

2022-01-27 14:58 UTC, khenrichsen commented on docs/swagger.yaml
> +    put:
Should we consider just having one get-endpoint, and accept Id or a list of id as a query parameter? Thats a pretty RESTful and normal way to handle get endpoints

2022-01-27 14:58 UTC, khenrichsen commented on docs/swagger.yaml
> +      description: Update redirectUrl
"Update the redirect url (target destination) of the QR"

2022-02-01 09:18 UTC, Sigvedash approved these changes

2022-02-01 09:19 UTC, merged

2022-02-01 17:49 UTC, khenrichsen commented on docs/swagger.yaml
> +      summary: Get all saleunit QRs
This wasnt added on all endpoints @kaffikaffi 
![image](https://user-images.githubusercontent.com/47554984/152022695-4f315d02-2dd8-4a62-8338-a1ff36860a5c.png)
its missing on delete and Get endpoints